# Site wide configuration

title: wiersma.org
locale: en_US
description: Functionally Dysfunctional
logo: site-logo.png
search: true
url: http://localhost:4000
#url: https://www.wiersma.org
wpm: 180

# Jekyll configuration

#permalink:   /:categories/:title/
permalink:    /:year/:month/:day/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess","toys"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Arjen Wiersma
  avatar: arjen.jpg
  email: arjen@wiersma.org
  disqus-shortname: wickeddutch
  twitter: credmp
  facebook: #username
  github: credmp
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: credmp
  instagram: credmp
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-20508870-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
